sudo: false
cache: pip

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

language: python

python:
  - "2.7"

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
  - WKHTMLTOPDF_VERSION="0.12.1"
  - WEBSITE_REPO="1"
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1"
  - TESTS="1" ODOO_REPO="OCA/OCB"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="website_signup_legal_page_required" MAKEPOT="1"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="website_signup_legal_page_required"

  # Module website_seo_redirection intercepts any HTTP request, so if you see
  # some abnormal behavior in your controllers and suspect this is the guilty
  # module, just enable these 2 lines below to check that.
  # - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="website_seo_redirection"
  # - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="website_seo_redirection"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install ipwhois

script:
  - travis_run_tests

after_success:
 - travis_after_tests_success
